# Generated by Django 4.2.5 on 2023-09-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastos',
            name='valor_despesa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
